In [1]:
import numpy as np

In [7]:
#1
vec = np.arange(10, 50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [132]:
#2
vec = np.arange(10, 50).np.


AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [49]:
#3
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [54]:
#4
ten = [[[0,1,2], [3,4,5], [6,7,8]], 
[[0,1,2], [3,4,5], [6,7,8]],
[[0,1,2], [3,4,5], [6,7,8]]]
ten

[[[0, 1, 2], [3, 4, 5], [6, 7, 8]],
 [[0, 1, 2], [3, 4, 5], [6, 7, 8]],
 [[0, 1, 2], [3, 4, 5], [6, 7, 8]]]

In [128]:
#5
vec = [1, 2, 0, 0, 4, 0]
vec[0:5]

[1, 2, 0, 0, 4]

In [110]:
#6
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [136]:
#7
ten = [[[0,1,2], [3,4,5], [6,7,8]], 
[[9,10,11], [12,13,14], [15,16,17]],
[[18,19,20], [21,22,23], [24,25,26]]]
np.argmax(ten), np.argmin(ten)

(26, 0)

In [145]:
#8
ten.mean()

6.5

In [160]:
#9
np.identity(n=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)