# Numpy Comparison

In [1]:
import numpy as np

## All & any

In [3]:
a = np. arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [5]:
np.any(a > 5), np.all(a > 5)

(True, False)

In [6]:
np.any(a > 10), np.all(a < 10)

(False, True)

## Logical operation

In [10]:
a = np.array([1, 3, 0], float)
b = np.logical_and(a>0, a<3)    # 0 < a < 3
b

array([ True, False, False])

In [11]:
c = np.logical_or (a<0, a>3)
c

array([False, False, False])

In [12]:
np.where(a > 0)

(array([0, 1], dtype=int64),)

In [14]:
# Nan --> Not a Number, np.NoN
# Inf --> Infinite, np.Inf
x = np.array([1, np.NaN, np.Inf])
x

array([ 1., nan, inf])

In [15]:
np.isnan(x)

array([False,  True, False])

In [21]:
np.isnan(x).sum()

1

In [ ]:
x = np.arange(1000, dtype=np.float32)
x[500] = np.NaN

In [24]:
np.isnan(x).sum()

1

In [25]:
np.isfinite(x)

array([ True, False, False])

In [27]:
len(x) - np.isfinite(x).sum()

2

## argmax & argmin

In [32]:
a = np.array([1,2,4,5,8,78,23,3])
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [34]:
np.argmax(a), np.argmin(a)

(5, 0)

In [35]:
a = np.array([[1,2,4,7],[9,88,6,45],[8,78,23,3]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 8, 78, 23,  3]])

In [36]:
np.argmax(a, axis=0)

array([1, 1, 2, 1], dtype=int64)

In [37]:
np.argmin(a, axis=1)

array([0, 2, 3], dtype=int64)